# Generated by Django 4.2.9 on 2024-04-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_category_receipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeapp.category'),
        ),
    ]
