# Generated by Django 4.2.9 on 2024-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_alter_receipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_ingredients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_making_process',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
