# Generated by Django 4.2.9 on 2024-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_receipe_receipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_ingredients',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
