# Generated by Django 5.0.6 on 2024-07-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dummy",
        ),
    ]
