# Generated by Django 5.0.6 on 2024-08-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0005_ab"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ab",
        ),
    ]
