# Generated by Django 5.0.6 on 2024-08-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0008_ba"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bac",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crudapp.ba",),
        ),
    ]
