# Generated by Django 5.0.6 on 2024-08-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0009_bac"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bacd",
            fields=[
                (
                    "ba_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crudapp.ba",
                    ),
                ),
                ("name6", models.CharField(default="", max_length=124)),
            ],
            bases=("crudapp.bac",),
        ),
    ]
