# Generated by Django 5.0.6 on 2024-08-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0010_bacd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bacd",
        ),
        migrations.CreateModel(
            name="Bacd",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crudapp.ba",),
        ),
    ]
