# Generated by Django 4.2.11 on 2024-05-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fitnessheadquater', '0002_categori_packs_delete_offer_applicant_apply_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SiteMember',
        ),
    ]
