# Generated by Django 4.2.11 on 2024-05-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fitnessheadquater', '0003_rename_users_sitemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteMember',
            new_name='User',
        ),
    ]
