# Generated by Django 4.2.11 on 2024-05-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnessheadquater', '0005_alter_member_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packs',
            name='discount',
        ),
        migrations.CreateModel(
            name='SiteMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessheadquater.sitemember'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
