# Generated by Django 4.2.11 on 2024-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessheadquater', '0006_remove_packs_discount_sitemember_alter_member_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packs',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
