# Generated by Django 4.2.11 on 2024-05-10 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessheadquater', '0009_alter_member_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessheadquater.categori'),
        ),
    ]
