# Generated by Django 4.2.11 on 2024-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessheadquater', '0010_alter_packs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pack',
        ),
        migrations.AddField(
            model_name='member',
            name='pack_duraton',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='pack_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
