# Generated by Django 4.2.11 on 2024-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessheadquater', '0011_remove_member_pack_member_pack_duraton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pack_price',
            field=models.IntegerField(null=True),
        ),
    ]
