# Generated by Django 5.0.6 on 2024-07-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fromapp", "0003_author_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="Author",
            new_name="author",
        ),
    ]
