# Generated by Django 5.0.6 on 2024-07-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fromapp", "0005_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Id",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="fromapp.id"
            ),
        ),
    ]
