# Generated by Django 5.0.6 on 2024-07-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImageComment",
            new_name="ImageCommentModel",
        ),
    ]
