# Generated by Django 5.0.6 on 2024-07-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapi", "0003_rename_imagelikedislike_imagelikedislikemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagelikedislikemodel",
            old_name="username",
            new_name="user",
        ),
    ]
