# Generated by Django 5.0.6 on 2024-07-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0005_imagecomment_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="h", max_length=300)),
                ("like", models.BooleanField(default=False)),
                ("dislike", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imageapp.imagemodel",
                    ),
                ),
            ],
        ),
    ]
