# Generated by Django 5.0.6 on 2024-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0020_user_alter_imagemodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="like",
            field=models.IntegerField(default=0, verbose_name="liked_numbers"),
        ),
    ]
