# Generated by Django 5.0.6 on 2024-07-04 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=500, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imageapp.imagemodel",
                    ),
                ),
            ],
        ),
    ]
