# Generated by Django 5.0.7 on 2024-08-05 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemodel",
            options={},
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploded By",
            ),
        ),
        migrations.AlterModelTable(
            name="imagemodel",
            table="jagdfjdsgfdj",
        ),
    ]
