# Generated by Django 5.0.7 on 2024-08-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_alter_imagemodel_options_alter_imagemodel_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemodel",
            options={"verbose_name": "Uploaded Images"},
        ),
        migrations.AlterModelTable(
            name="imagemodel",
            table="Uploaded Images",
        ),
    ]
