# Generated by Django 5.0.6 on 2024-07-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_imagecomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="comment",
        ),
    ]
