# Generated by Django 5.0.6 on 2024-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0003_remove_imagemodel_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecomment",
            name="created_at",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
