# Generated by Django 5.0.6 on 2024-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0004_imagecomment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecomment",
            name="username",
            field=models.CharField(default="h", max_length=300),
        ),
    ]
