# Generated by Django 5.0.7 on 2024-08-06 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0005_rename_follower_followermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecomment",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
