# Generated by Django 5.0.6 on 2024-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0006_imagelike"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="comment",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
