# Generated by Django 5.0.7 on 2024-08-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0006_alter_imagecomment_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagecomment",
            old_name="username",
            new_name="user",
        ),
    ]
