# Generated by Django 5.0.7 on 2024-08-07 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0007_rename_username_imagecomment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followermodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="post_admin",
            ),
        ),
    ]
