# Generated by Django 5.0.6 on 2024-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0008_imagemodel_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yellow", "Yellow"),
                    ("red", "Red"),
                    ("black", "Black"),
                    ("yalk", "Yalk"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
