# Generated by Django 5.0.6 on 2024-07-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0009_imagemodel_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="color",
        ),
    ]
