# Generated by Django 5.0.6 on 2024-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0010_remove_imagemodel_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="pofile_image",
            field=models.ImageField(null=True, upload_to="profile_image"),
        ),
    ]
