# Generated by Django 5.0.6 on 2024-07-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0011_imagemodel_pofile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_image", models.ImageField(null=True, upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="pofile_image",
            field=models.ImageField(null=True, upload_to="media"),
        ),
    ]
