# Generated by Django 5.0.6 on 2024-07-16 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0012_profileimage_alter_imagemodel_pofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="pofile_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="imageapp.profileimage",
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="media"),
        ),
    ]
