# Generated by Django 5.0.6 on 2024-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0013_alter_imagemodel_pofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="pofile_image",
            field=models.ImageField(null=True, upload_to="media"),
        ),
        migrations.DeleteModel(
            name="ProfileImage",
        ),
    ]
