# Generated by Django 5.0.6 on 2024-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0017_remove_imagemodel_pofile_image_delete_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
