# Generated by Django 5.0.6 on 2024-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0018_imagemodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="created_at",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
