# Generated by Django 5.0.6 on 2024-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
