# Generated by Django 5.0.6 on 2024-08-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0002_alter_studentinfo_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
