# Generated by Django 5.0.7 on 2024-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0003_alter_studentinfo_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
