# Generated by Django 5.0.6 on 2024-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
